server:
  port: 0

spring:
  application:
    name: srv-b

  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}-${random.uuid}
        health:
          check:
            interval: 30s
